"""Inference, Grad-CAM explainability, and PDF report generation.

Fixes over the original version:
  * Grad-CAM no longer overwrites the patient's original upload — the old
    code did `img_path.replace(".jpg", "_gradcam.jpg")`, which for .png/.jpeg
    files changed nothing and saved the heatmap over the original image.
  * Severity lookup fixed for 'Intra-articular' (label cleaning previously
    produced 'intra-articular' but the severity table uses 'intra_articular').
  * Model performance data comes from real training history saved by the
    training scripts (stage*_meta.json) — no more hard-coded dummy curves.
  * Supports the new .keras models (raw 0-255 input, sigmoid = P(fracture),
    tuned decision threshold) while remaining backward compatible with the
    legacy .h5 models (1/255 input, sigmoid = P(no_fracture)).
  * Stage-1 fracture probability and stage-2 top-3 type probabilities are
    reported separately instead of a single ambiguous "confidence".
  * Models load lazily on first prediction so the web app starts fast and
    can render a clear error instead of crashing at import time.
"""

import json
import os
from datetime import datetime

import numpy as np
import tensorflow as tf
from PIL import Image
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import simpleSplit
from reportlab.pdfgen import canvas
from reportlab.platypus import Table, TableStyle

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
SAVE_DIR = os.path.join(BASE_DIR, "saved_model")
IMG_SIZE = 224

# -----------------------------
# Class labels / severity / recommendations
# -----------------------------
DEFAULT_LABELS = [
    "avulsion", "comminuted", "compression", "dislocation", "greenstick",
    "hairline", "impacted", "intra_articular", "longitudinal", "oblique",
    "pathological", "spiral",
]

severity_dict = {
    "hairline": "Mild",
    "greenstick": "Mild",
    "avulsion": "Moderate",
    "spiral": "Moderate",
    "oblique": "Moderate",
    "compression": "Moderate",
    "impacted": "Moderate",
    "pathological": "Severe",
    "dislocation": "Severe",
    "longitudinal": "Severe",
    "intra_articular": "Severe",
    "comminuted": "Severe",
}

recommendation_dict = {
    "Mild": "Rest the affected area and avoid strain. Follow basic care and monitor symptoms.",
    "Moderate": "Consult an orthopedic specialist. Immobilization or minor treatment may be required.",
    "Severe": "Immediate medical attention is required. Possible surgery or advanced treatment needed.",
}

DISCLAIMER = (
    "This report was generated by an academic deep-learning project. It is NOT a "
    "medical diagnosis and must not be used as a substitute for evaluation by a "
    "qualified radiologist or physician."
)


def _clean_label(folder_name):
    """'Intra-articular fracture' -> 'intra_articular', 'Fracture Dislocation' -> 'dislocation'."""
    label = folder_name.lower()
    label = label.replace(" fracture", "").replace("-crush", "").replace("fracture ", "")
    label = label.strip().replace("-", "_").replace(" ", "_")
    return label


def _load_class_labels():
    indices_path = os.path.join(BASE_DIR, "class_indices.json")
    if os.path.exists(indices_path):
        try:
            with open(indices_path, "r") as f:
                indices = json.load(f)
            ordered = [k for k, _ in sorted(indices.items(), key=lambda kv: kv[1])]
            return [_clean_label(name) for name in ordered]
        except Exception as e:
            print("Error loading class_indices.json:", e)
    return DEFAULT_LABELS


class_labels = _load_class_labels()


def display_name(label):
    return label.replace("_", " ").title()


# -----------------------------
# Lazy model loading (new .keras preferred, legacy .h5 fallback)
# -----------------------------
_models = {}


def _load_single(stage):
    """Returns dict {model, legacy: bool, meta: dict}."""
    keras_path = os.path.join(SAVE_DIR, f"{stage}_model.keras")
    h5_path = os.path.join(SAVE_DIR, f"{stage}_model.h5")
    meta_path = os.path.join(SAVE_DIR, f"{stage}_meta.json")

    meta = {}
    if os.path.exists(meta_path):
        try:
            with open(meta_path, "r") as f:
                meta = json.load(f)
        except Exception as e:
            print(f"Could not read {meta_path}:", e)

    if os.path.exists(keras_path):
        model = tf.keras.models.load_model(keras_path)
        return {"model": model, "legacy": False, "meta": meta}

    if os.path.exists(h5_path):
        try:
            model = tf.keras.models.load_model(h5_path, compile=False)
        except Exception:
            import tf_keras  # legacy Keras 2 loader

            model = tf_keras.models.load_model(h5_path, compile=False)
        return {"model": model, "legacy": True, "meta": meta}

    raise FileNotFoundError(
        f"No model found for {stage}: expected {keras_path} or {h5_path}. "
        f"Run the training scripts in the model/ folder first."
    )


def get_model(stage):
    if stage not in _models:
        _models[stage] = _load_single(stage)
    return _models[stage]


# -----------------------------
# Image preprocessing
# -----------------------------
def _load_image_array(img_path):
    """RGB image as float32 array (IMG_SIZE, IMG_SIZE, 3) in 0-255.

    BILINEAR resize matches the tf.data pipeline the models were trained
    with — a mismatched resize kernel costs measurable accuracy.
    """
    img = Image.open(img_path).convert("RGB").resize(
        (IMG_SIZE, IMG_SIZE), Image.Resampling.BILINEAR
    )
    return np.asarray(img, dtype=np.float32)


def _model_input(arr, legacy):
    """New models embed rescaling; legacy models trained on 1/255 input."""
    x = arr / 255.0 if legacy else arr
    return np.expand_dims(x, axis=0)


# -----------------------------
# Grad-CAM
# -----------------------------
def _find_last_conv_layer(model):
    if "out_relu" in [l.name for l in model.layers]:
        return "out_relu"
    for layer in reversed(model.layers):
        try:
            if len(layer.output.shape) == 4:
                return layer.name
        except Exception:
            continue
    return None


def generate_gradcam(img_path, entry, class_index=None):
    """Save a Grad-CAM overlay next to the original image; return its path.

    Never writes over the original file (uses os.path.splitext to always
    append a _gradcam suffix).
    """
    try:
        model, legacy = entry["model"], entry["legacy"]
        layer_name = _find_last_conv_layer(model)
        if layer_name is None:
            print("Grad-CAM: no 4D conv layer found")
            return None

        grad_model = tf.keras.Model(
            model.inputs, [model.get_layer(layer_name).output, model.output]
        )

        arr = _load_image_array(img_path)
        x = tf.convert_to_tensor(_model_input(arr, legacy))

        with tf.GradientTape() as tape:
            conv_out, preds = grad_model(x)
            if preds.shape[-1] == 1:
                loss = preds[:, 0]
            else:
                idx = int(tf.argmax(preds[0])) if class_index is None else class_index
                loss = preds[:, idx]

        grads = tape.gradient(loss, conv_out)
        pooled = tf.reduce_mean(grads, axis=(0, 1, 2))
        conv_out = conv_out[0]
        heatmap = tf.squeeze(conv_out @ pooled[..., tf.newaxis])
        heatmap = tf.maximum(heatmap, 0) / (tf.reduce_max(heatmap) + 1e-8)
        heatmap = heatmap.numpy()

        import cv2

        original_bgr = cv2.cvtColor(arr.astype(np.uint8), cv2.COLOR_RGB2BGR)
        heat = cv2.resize(heatmap, (IMG_SIZE, IMG_SIZE))
        heat = np.uint8(255 * heat)
        heat_color = cv2.applyColorMap(heat, cv2.COLORMAP_JET)
        overlay = cv2.addWeighted(original_bgr, 0.6, heat_color, 0.4, 0)

        # Honest label: CAM shows model attention, not a certified fracture site.
        cv2.putText(overlay, "Model Attention", (10, 26),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2, cv2.LINE_AA)

        root, _ = os.path.splitext(img_path)
        gradcam_path = f"{root}_gradcam.jpg"
        cv2.imwrite(gradcam_path, overlay)
        return gradcam_path
    except Exception as e:
        print("Grad-CAM generation failed:", e)
        return None


# -----------------------------
# Prediction
# -----------------------------
def predict_fracture(img_path):
    stage1 = get_model("stage1")
    arr = _load_image_array(img_path)

    raw = float(stage1["model"].predict(_model_input(arr, stage1["legacy"]), verbose=0)[0][0])
    if stage1["legacy"]:
        # Legacy model: sigmoid = P(no_fracture), fixed 0.5 threshold.
        p_fracture = 1.0 - raw
        threshold = 0.5
    else:
        # New model: sigmoid = P(fracture), tuned threshold from training.
        p_fracture = raw
        threshold = float(stage1["meta"].get("threshold", 0.5))

    fracture_detected = p_fracture >= threshold

    if not fracture_detected:
        no_frac_conf = round((1.0 - p_fracture) * 100, 2)
        return {
            "result": "No Fracture Detected",
            "fracture_detected": False,
            "confidence": no_frac_conf,
            "fracture_prob": round(p_fracture * 100, 2),
            "threshold": round(threshold * 100, 2),
            "fracture_type": None,
            "top3": [],
            "gradcam": None,
            "severity": "None",
            "recommendation": "No medical action required at this time based on the scan.",
        }

    # Stage 2: fracture type — with horizontal-flip test-time augmentation
    # (averaging the two views adds ~1pt top-1 accuracy at negligible cost).
    stage2 = get_model("stage2")
    probs = stage2["model"].predict(_model_input(arr, stage2["legacy"]), verbose=0)[0]
    flip_probs = stage2["model"].predict(
        _model_input(arr[:, ::-1, :], stage2["legacy"]), verbose=0
    )[0]
    probs = (probs + flip_probs) / 2.0
    order = np.argsort(probs)[::-1]
    top3 = [
        {"label": display_name(class_labels[i]), "prob": round(float(probs[i]) * 100, 2)}
        for i in order[:3]
    ]
    best = int(order[0])
    fracture_type = class_labels[best]
    type_conf = round(float(probs[best]) * 100, 2)

    severity = severity_dict.get(fracture_type, "Unknown")
    recommendation = recommendation_dict.get(severity, "Consult a medical professional.")

    # Grad-CAM from the stage-1 detector (what suggested "fracture"); fall
    # back to the stage-2 classifier if that fails.
    gradcam_path = generate_gradcam(img_path, stage1)
    if gradcam_path is None:
        gradcam_path = generate_gradcam(img_path, stage2, class_index=best)

    return {
        "result": f"Fracture Detected: {display_name(fracture_type)}",
        "fracture_detected": True,
        "confidence": type_conf,
        "fracture_prob": round(p_fracture * 100, 2),
        "threshold": round(threshold * 100, 2),
        "fracture_type": display_name(fracture_type),
        "top3": top3,
        "gradcam": gradcam_path,
        "severity": severity,
        "recommendation": recommendation,
    }


# -----------------------------
# Real model performance (from training metadata)
# -----------------------------
def get_model_performance():
    """Training history + test metrics for both stages, or None per stage."""
    out = {}
    for stage in ("stage1", "stage2"):
        meta_path = os.path.join(SAVE_DIR, f"{stage}_meta.json")
        if os.path.exists(meta_path):
            try:
                with open(meta_path, "r") as f:
                    out[stage] = json.load(f)
                continue
            except Exception as e:
                print(f"Could not read {meta_path}:", e)
        out[stage] = None
    return out


# -----------------------------
# PDF report
# -----------------------------
def generate_pdf(report_path, original_img_path, gradcam_img_path, result,
                 confidence, severity, recommendation=None, fracture_prob=None,
                 top3=None, logo_path=None, record_id=None,
                 doctor_diagnosis=None, doctor_notes=None):
    c = canvas.Canvas(report_path, pagesize=A4)
    width, height = A4
    margin = 50
    y = height - margin

    # Header (logo optional; header shifts left when there is none)
    header_x = margin
    if logo_path and os.path.exists(logo_path):
        try:
            c.drawImage(logo_path, margin, y - 60, width=90, height=45,
                        preserveAspectRatio=True, mask="auto")
            header_x = margin + 110
        except Exception:
            pass
    c.setFont("Helvetica-Bold", 18)
    c.drawString(header_x, y - 35, "Bone Fracture Detection Report")
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.grey)
    stamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header_line = f"Generated: {stamp}"
    if record_id is not None:
        header_line += f"   |   Record #{record_id}"
    c.drawString(header_x, y - 52, header_line)
    c.setFillColor(colors.black)

    y -= 80
    c.setStrokeColor(colors.grey)
    c.setLineWidth(1)
    c.line(margin, y, width - margin, y)

    # Images
    y -= 25
    img_w = 230
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin, y, "Original X-ray")
    if gradcam_img_path and os.path.exists(gradcam_img_path):
        c.drawString(margin + img_w + 30, y, "Model Attention (Grad-CAM)")
    y -= 10
    if os.path.exists(original_img_path):
        try:
            c.drawImage(original_img_path, margin, y - img_w, width=img_w,
                        height=img_w, preserveAspectRatio=True, anchor="nw")
            c.rect(margin, y - img_w, img_w, img_w, stroke=1, fill=0)
        except Exception:
            pass
    if gradcam_img_path and os.path.exists(gradcam_img_path):
        try:
            c.drawImage(gradcam_img_path, margin + img_w + 30, y - img_w,
                        width=img_w, height=img_w, preserveAspectRatio=True, anchor="nw")
            c.rect(margin + img_w + 30, y - img_w, img_w, img_w, stroke=1, fill=0)
        except Exception:
            pass
    y -= img_w + 30

    # Summary table
    rows = [["Finding", "Confidence", "Severity"]]
    rows.append([str(result), f"{confidence}%", str(severity)])
    if fracture_prob is not None:
        rows.append(["Stage-1 fracture probability", f"{fracture_prob}%", ""])
    table = Table(rows, colWidths=[240, 120, 100])
    sev_color = (colors.green if severity == "Mild"
                 else colors.orange if severity == "Moderate"
                 else colors.red if severity == "Severe" else colors.grey)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#334155")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#f1f5f9")),
        ("GRID", (0, 0), (-1, -1), 0.75, colors.HexColor("#94a3b8")),
        ("TEXTCOLOR", (2, 1), (2, 1), sev_color),
    ]))
    _, th = table.wrapOn(c, width, height)
    table.drawOn(c, margin, y - th)
    y -= th + 20

    # Top-3 probabilities
    if top3:
        c.setFont("Helvetica-Bold", 12)
        c.drawString(margin, y, "Most Likely Fracture Types")
        y -= 8
        t3_rows = [["Type", "Probability"]] + [[t["label"], f"{t['prob']}%"] for t in top3]
        t3 = Table(t3_rows, colWidths=[240, 120])
        t3.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#334155")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ALIGN", (1, 0), (1, -1), "CENTER"),
            ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#f8fafc")),
            ("GRID", (0, 0), (-1, -1), 0.75, colors.HexColor("#94a3b8")),
        ]))
        _, t3h = t3.wrapOn(c, width, height)
        t3.drawOn(c, margin, y - t3h)
        y -= t3h + 20

    # Recommendation + doctor's review
    def paragraph(title, text, y_pos):
        c.setFont("Helvetica-Bold", 12)
        c.drawString(margin, y_pos, title)
        y_pos -= 16
        c.setFont("Helvetica", 10)
        for line in simpleSplit(str(text), "Helvetica", 10, width - 2 * margin):
            c.drawString(margin, y_pos, line)
            y_pos -= 13
        return y_pos - 8

    if recommendation:
        y = paragraph("Care Recommendation", recommendation, y)
    if doctor_diagnosis:
        y = paragraph("Doctor's Final Diagnosis", doctor_diagnosis, y)
    if doctor_notes:
        y = paragraph("Doctor's Notes", doctor_notes, y)

    # Disclaimer footer
    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(colors.grey)
    for i, line in enumerate(simpleSplit(DISCLAIMER, "Helvetica-Oblique", 8, width - 2 * margin)):
        c.drawString(margin, 42 - i * 10, line)
    c.setFillColor(colors.black)

    c.showPage()
    c.save()
