"""PDF report generation and server-side image rendering.

Split out of predict.py so the inference pipeline and the reporting layer
can evolve independently. Also renders doctor annotations (vector JSON →
flattened PNG) and detector bounding boxes onto image copies — the server
render is the canonical one; client-exported bitmaps are never trusted.
"""

import json
import math
import os
from datetime import datetime

from PIL import Image, ImageDraw, ImageFont
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import simpleSplit
from reportlab.pdfgen import canvas
from reportlab.platypus import Table, TableStyle

DISCLAIMER = (
    "This report was generated by an academic deep-learning project. It is NOT a "
    "medical diagnosis and must not be used as a substitute for evaluation by a "
    "qualified radiologist or physician."
)

LOCALIZATION_CAVEAT = (
    "Localization (beta) — the region detector was validated on wrist radiographs "
    "only; boxes outside wrist studies are unreliable."
)


# -----------------------------
# Server-side annotation flattening (vector JSON -> PNG)
# -----------------------------
def _font(size):
    """A scalable font without bundling a TTF (Pillow >= 10.1)."""
    try:
        return ImageFont.load_default(size=size)
    except TypeError:  # very old Pillow
        return ImageFont.load_default()


def _draw_arrow(draw, x1, y1, x2, y2, color, width):
    draw.line([(x1, y1), (x2, y2)], fill=color, width=width)
    # Arrowhead at (x2, y2)
    angle = math.atan2(y2 - y1, x2 - x1)
    head = max(10, width * 4)
    for offset in (math.pi / 7, -math.pi / 7):
        hx = x2 - head * math.cos(angle + offset)
        hy = y2 - head * math.sin(angle + offset)
        draw.line([(x2, y2), (hx, hy)], fill=color, width=width)


def flatten_annotations(original_img_path, annotations, out_path):
    """Render doctor annotation JSON onto a copy of the original image.

    `annotations` is either the JSON dict ({image_w, image_h, shapes: [...]})
    or a list of such dicts (multiple saved reviews — drawn in order).
    Coordinates are normalized 0-1, so any display resolution re-renders
    identically. Returns out_path, or None if there was nothing to draw.
    """
    if annotations is None:
        return None
    if isinstance(annotations, str):
        annotations = json.loads(annotations)
    layers = annotations if isinstance(annotations, list) else [annotations]
    shapes = [s for layer in layers for s in layer.get("shapes", [])]
    if not shapes:
        return None

    img = Image.open(original_img_path).convert("RGB")
    w, h = img.size
    draw = ImageDraw.Draw(img)
    # Stroke widths in the JSON are relative to a ~1000px canvas.
    scale = max(w, h) / 1000.0

    for s in shapes:
        color = s.get("color", "#ff5252")
        width = max(1, round(float(s.get("width", 3)) * scale))
        kind = s.get("type")
        if kind == "ellipse":
            cx, cy = s["cx"] * w, s["cy"] * h
            rx, ry = s["rx"] * w, s["ry"] * h
            draw.ellipse([cx - rx, cy - ry, cx + rx, cy + ry], outline=color, width=width)
        elif kind == "arrow":
            _draw_arrow(draw, s["x1"] * w, s["y1"] * h, s["x2"] * w, s["y2"] * h, color, width)
        elif kind == "path":
            pts = [(p[0] * w, p[1] * h) for p in s.get("points", [])]
            if len(pts) >= 2:
                draw.line(pts, fill=color, width=width, joint="curve")
        elif kind == "label":
            text = str(s.get("text", ""))[:120]
            if not text:
                continue
            font = _font(max(14, round(16 * scale)))
            x, y = s["x"] * w, s["y"] * h
            bbox = draw.textbbox((x, y), text, font=font)
            pad = 3
            draw.rectangle(
                [bbox[0] - pad, bbox[1] - pad, bbox[2] + pad, bbox[3] + pad],
                fill=(0, 0, 0, 200),
            )
            draw.text((x, y), text, fill=color, font=font)

    img.save(out_path)
    return out_path


def render_detections(original_img_path, detections, out_path):
    """Draw detector boxes (normalized x,y,w,h + conf) onto an image copy."""
    if not detections:
        return None
    if isinstance(detections, str):
        detections = json.loads(detections)
    img = Image.open(original_img_path).convert("RGB")
    w, h = img.size
    draw = ImageDraw.Draw(img)
    scale = max(w, h) / 1000.0
    width = max(2, round(3 * scale))
    font = _font(max(14, round(16 * scale)))
    for det in detections:
        x0, y0 = det["x"] * w, det["y"] * h
        x1, y1 = x0 + det["w"] * w, y0 + det["h"] * h
        draw.rectangle([x0, y0, x1, y1], outline="#22d3ee", width=width)
        label = f"fracture {det.get('conf', 0):.0%}"
        bbox = draw.textbbox((x0, max(0, y0 - 20 * scale)), label, font=font)
        draw.rectangle(bbox, fill="#0e7490")
        draw.text((x0, max(0, y0 - 20 * scale)), label, fill="white", font=font)
    img.save(out_path)
    return out_path


# -----------------------------
# PDF report
# -----------------------------
def generate_pdf(report_path, original_img_path, gradcam_img_path, result,
                 confidence, severity, recommendation=None, fracture_prob=None,
                 top3=None, logo_path=None, record_id=None,
                 doctor_diagnosis=None, doctor_notes=None,
                 verdict=None, tier_text=None, threshold=None,
                 abstain_low=None, abstain_high=None, type_unclear=False,
                 annotated_img_path=None, detections=None,
                 body_part=None, view_position=None):
    c = canvas.Canvas(report_path, pagesize=A4)
    width, height = A4
    margin = 50
    y = height - margin

    # Header (logo optional; header shifts left when there is none)
    header_x = margin
    if logo_path and os.path.exists(logo_path):
        try:
            c.drawImage(logo_path, margin, y - 60, width=90, height=45,
                        preserveAspectRatio=True, mask="auto")
            header_x = margin + 110
        except Exception:
            pass
    c.setFont("Helvetica-Bold", 18)
    c.drawString(header_x, y - 35, "Bone Fracture Detection Report")
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.grey)
    stamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header_line = f"Generated: {stamp}"
    if record_id is not None:
        header_line += f"   |   Record #{record_id}"
    c.drawString(header_x, y - 52, header_line)
    c.setFillColor(colors.black)

    y -= 80
    c.setStrokeColor(colors.grey)
    c.setLineWidth(1)
    c.line(margin, y, width - margin, y)

    # Plain-language tier — the same wording shown in the app.
    if tier_text:
        y -= 22
        c.setFont("Helvetica-Bold", 12)
        c.setFillColor(colors.HexColor("#334155"))
        c.drawString(margin, y, tier_text)
        c.setFillColor(colors.black)
        y -= 3

    # Images: left = annotated original (if the doctor drew) or detection
    # render or plain original; right = Grad-CAM merged overlay.
    y -= 25
    img_w = 230
    left_path, left_label = original_img_path, "Original X-ray"
    if annotated_img_path and os.path.exists(annotated_img_path):
        left_path, left_label = annotated_img_path, "Doctor's Annotations"
    elif detections:
        boxed = os.path.splitext(report_path)[0] + "_boxes.png"
        try:
            if render_detections(original_img_path, detections, boxed):
                left_path, left_label = boxed, "Detected Region(s) — beta"
        except Exception:
            pass

    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin, y, left_label)
    if gradcam_img_path and os.path.exists(gradcam_img_path):
        c.drawString(margin + img_w + 30, y, "Model Attention (Grad-CAM)")
    y -= 10
    if left_path and os.path.exists(left_path):
        try:
            c.drawImage(left_path, margin, y - img_w, width=img_w,
                        height=img_w, preserveAspectRatio=True, anchor="nw")
            c.rect(margin, y - img_w, img_w, img_w, stroke=1, fill=0)
        except Exception:
            pass
    if gradcam_img_path and os.path.exists(gradcam_img_path):
        try:
            c.drawImage(gradcam_img_path, margin + img_w + 30, y - img_w,
                        width=img_w, height=img_w, preserveAspectRatio=True, anchor="nw")
            c.rect(margin + img_w + 30, y - img_w, img_w, img_w, stroke=1, fill=0)
        except Exception:
            pass
    y -= img_w + 15

    if detections:
        c.setFont("Helvetica-Oblique", 8)
        c.setFillColor(colors.grey)
        for line in simpleSplit(LOCALIZATION_CAVEAT, "Helvetica-Oblique", 8, width - 2 * margin):
            c.drawString(margin, y, line)
            y -= 10
        c.setFillColor(colors.black)
    y -= 12

    # Summary table
    rows = [["Finding", "Confidence", "Severity"]]
    rows.append([str(result), f"{confidence}%", str(severity)])
    if fracture_prob is not None:
        prob_note = f"{fracture_prob}%"
        if threshold is not None:
            prob_note += f"  (threshold {threshold}%)"
        rows.append(["Calibrated fracture probability", prob_note, ""])
    if abstain_low is not None and abstain_high is not None:
        rows.append(["Abstention band (auto-review)",
                     f"{abstain_low}% – {abstain_high}%", ""])
    if body_part or view_position:
        rows.append(["Body part / view",
                     f"{body_part or '—'} / {view_position or '—'}", ""])
    table = Table(rows, colWidths=[240, 160, 80])
    sev_color = (colors.green if severity == "Mild"
                 else colors.orange if severity == "Moderate"
                 else colors.red if severity == "Severe" else colors.grey)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#334155")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#f1f5f9")),
        ("GRID", (0, 0), (-1, -1), 0.75, colors.HexColor("#94a3b8")),
        ("TEXTCOLOR", (2, 1), (2, 1), sev_color),
    ]))
    _, th = table.wrapOn(c, width, height)
    table.drawOn(c, margin, y - th)
    y -= th + 20

    # Top-3 probabilities
    if top3:
        c.setFont("Helvetica-Bold", 12)
        header = ("Fracture Type Unclear — Most Likely Candidates"
                  if type_unclear else "Most Likely Fracture Types")
        c.drawString(margin, y, header)
        y -= 8
        t3_rows = [["Type", "Probability"]] + [[t["label"], f"{t['prob']}%"] for t in top3]
        t3 = Table(t3_rows, colWidths=[240, 120])
        t3.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#334155")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ALIGN", (1, 0), (1, -1), "CENTER"),
            ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#f8fafc")),
            ("GRID", (0, 0), (-1, -1), 0.75, colors.HexColor("#94a3b8")),
        ]))
        _, t3h = t3.wrapOn(c, width, height)
        t3.drawOn(c, margin, y - t3h)
        y -= t3h + 20

    # Recommendation + doctor's review
    def paragraph(title, text, y_pos):
        c.setFont("Helvetica-Bold", 12)
        c.drawString(margin, y_pos, title)
        y_pos -= 16
        c.setFont("Helvetica", 10)
        for line in simpleSplit(str(text), "Helvetica", 10, width - 2 * margin):
            c.drawString(margin, y_pos, line)
            y_pos -= 13
        return y_pos - 8

    if recommendation:
        y = paragraph("Care Recommendation", recommendation, y)
    if doctor_diagnosis:
        y = paragraph("Doctor's Final Diagnosis", doctor_diagnosis, y)
    if doctor_notes:
        y = paragraph("Doctor's Notes", doctor_notes, y)

    # Disclaimer footer
    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(colors.grey)
    for i, line in enumerate(simpleSplit(DISCLAIMER, "Helvetica-Oblique", 8, width - 2 * margin)):
        c.drawString(margin, 42 - i * 10, line)
    c.setFillColor(colors.black)

    c.showPage()
    c.save()
